-- Seed 105 test products (15 per category) with metadata
-- Uses placeholder images from picsum.photos
-- Uses ON CONFLICT (slug) DO NOTHING so this migration is idempotent

-- ══════════════════════════════════════════════════════════════════════════════
-- NECKLACES (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Royal Kundan Choker', 'royal-kundan-choker', 'Exquisite kundan choker necklace with intricate meenakari work on the reverse. Perfect for bridal occasions with its regal design featuring polki stones and pearl drops.', 189.99, 249.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk1/600/600', 'https://picsum.photos/seed/nk1b/600/600'], 12, true, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['bridal', 'kundan', 'choker', 'wedding']),
('Temple Gold Long Necklace', 'temple-gold-long-necklace', 'Traditional South Indian temple jewelry long necklace with Lakshmi pendant and ruby stone accents. A timeless piece for festive celebrations.', 159.99, 199.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk2/600/600', 'https://picsum.photos/seed/nk2b/600/600'], 18, true, true, 'Temple', 'Gold', 'Festival', 'Traditional', ARRAY['temple', 'south-indian', 'festival', 'gold']),
('Layered Pearl Chain Necklace', 'layered-pearl-chain-necklace', 'Elegant multi-layered pearl chain necklace with gold-plated connectors. A versatile piece that adds sophistication to any outfit.', 49.99, 69.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk3/600/600', 'https://picsum.photos/seed/nk3b/600/600'], 35, false, true, 'Pearl', 'White', 'Party', 'Modern', ARRAY['pearl', 'layered', 'party', 'elegant']),
('Oxidized Silver Tribal Necklace', 'oxidized-silver-tribal-necklace', 'Bold oxidized silver tribal necklace with geometric patterns inspired by ancient Indian motifs. A statement piece for the modern bohemian.', 39.99, 54.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk4/600/600', 'https://picsum.photos/seed/nk4b/600/600'], 28, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['oxidized', 'tribal', 'boho', 'statement']),
('Meenakari Rani Haar', 'meenakari-rani-haar', 'Stunning meenakari rani haar (queen''s necklace) in vibrant green and red enamel on gold-plated base. Two-tiered design with matching beads.', 129.99, 169.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk5/600/600', 'https://picsum.photos/seed/nk5b/600/600'], 15, true, true, 'Meenakari', 'Multi', 'Wedding', 'Traditional', ARRAY['meenakari', 'rani-haar', 'bridal', 'colorful']),
('Rose Gold Minimalist Pendant Chain', 'rose-gold-minimalist-pendant-chain', 'Delicate rose gold-plated chain with a tiny heart pendant. Perfect for everyday wear — lightweight and comfortable for all-day styling.', 24.99, 34.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk6/600/600'], 45, false, true, 'Gold Plated', 'Rose Gold', 'Daily Wear', 'Minimalist', ARRAY['minimalist', 'daily-wear', 'rose-gold', 'pendant']),
('Polki Diamond Bridal Set Necklace', 'polki-diamond-bridal-set-necklace', 'Magnificent polki diamond-style bridal necklace with cascading pearl strings and emerald green stones. The centerpiece of any bridal ensemble.', 249.99, 329.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk7/600/600', 'https://picsum.photos/seed/nk7b/600/600'], 8, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['bridal', 'polki', 'diamond', 'luxury']),
('Antique Gold Coin Necklace', 'antique-gold-coin-necklace', 'Heritage-inspired antique gold coin necklace (kasumalai) featuring Lakshmi coins in a graduated design. A South Indian classic.', 119.99, 149.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk8/600/600'], 22, false, true, 'Gold Plated', 'Gold', 'Festival', 'Classic', ARRAY['antique', 'coin', 'south-indian', 'kasumalai']),
('Crystal Statement Collar', 'crystal-statement-collar', 'Glamorous crystal-studded collar necklace with adjustable back chain. Catches light beautifully — perfect for evening parties and cocktail events.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk9/600/600'], 30, false, true, 'Silver Plated', 'Silver', 'Party', 'Statement', ARRAY['crystal', 'statement', 'party', 'glamorous']),
('Fusion Geometric Chain Necklace', 'fusion-geometric-chain-necklace', 'Contemporary fusion necklace combining traditional Indian motifs with modern geometric shapes. Gold-plated with matte finish sections.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk10/600/600'], 25, false, true, 'Gold Plated', 'Gold', 'Office', 'Fusion', ARRAY['fusion', 'geometric', 'modern', 'office']),
('Kundan Bridal Necklace Set', 'kundan-bridal-necklace-set', 'Opulent kundan bridal necklace with matching earrings and maang tikka. Heavy-set design with uncut stone replicas and pearl borders.', 279.99, null, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk11/600/600', 'https://picsum.photos/seed/nk11b/600/600'], 6, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['kundan', 'bridal', 'set', 'heavy']),
('Silver Filigree Collar', 'silver-filigree-collar', 'Intricately crafted silver-plated filigree collar necklace inspired by Cuttack silverwork. Lightweight despite its ornate appearance.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk12/600/600'], 20, false, true, 'Silver Plated', 'Silver', 'Party', 'Classic', ARRAY['filigree', 'silver', 'cuttack', 'classic']),
('Pearl Choker with Kundan Pendant', 'pearl-choker-kundan-pendant', 'Elegant multi-strand pearl choker with a central kundan pendant drop. Perfect for sangeet and reception parties.', 89.99, 119.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk13/600/600'], 16, false, true, 'Pearl', 'White', 'Wedding', 'Fusion', ARRAY['pearl', 'choker', 'kundan', 'sangeet']),
('Green Onyx Beaded Necklace', 'green-onyx-beaded-necklace', 'Natural green onyx beaded necklace with gold-plated spacers. Earthy elegance for the conscious fashionista.', 34.99, 49.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk14/600/600'], 40, false, true, 'Gold Plated', 'Green', 'Casual', 'Boho', ARRAY['beaded', 'green', 'onyx', 'natural']),
('Jadau Gulband Choker', 'jadau-gulband-choker', 'Rajasthani jadau gulband choker with fine enamel work and uncut stone settings. A royal treasure for traditional celebrations.', 199.99, 259.99, (SELECT id FROM categories WHERE slug = 'necklaces'), ARRAY['https://picsum.photos/seed/nk15/600/600', 'https://picsum.photos/seed/nk15b/600/600'], 10, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'gulband', 'rajasthani', 'bridal'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- EARRINGS (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Classic Gold Jhumka Earrings', 'classic-gold-jhumka-earrings', 'Timeless gold-plated jhumka earrings with delicate bell-shaped drops and filigree detailing. The quintessential Indian earring for every occasion.', 34.99, 49.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er1/600/600', 'https://picsum.photos/seed/er1b/600/600'], 50, true, true, 'Gold Plated', 'Gold', 'Festival', 'Traditional', ARRAY['jhumka', 'traditional', 'gold', 'classic']),
('Kundan Chandbali Earrings', 'kundan-chandbali-earrings', 'Magnificent crescent-shaped chandbali earrings with kundan stones and pearl tassels. A showstopper for bridal and festive events.', 79.99, 109.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er2/600/600', 'https://picsum.photos/seed/er2b/600/600'], 20, true, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['chandbali', 'kundan', 'bridal', 'pearls']),
('Diamond-Style Stud Earrings', 'diamond-style-stud-earrings', 'Sparkling cubic zirconia stud earrings in silver-plated settings. Everyday elegance that goes with everything in your wardrobe.', 19.99, 29.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er3/600/600'], 45, false, true, 'Silver Plated', 'Silver', 'Daily Wear', 'Minimalist', ARRAY['studs', 'diamond', 'daily-wear', 'minimalist']),
('Oxidized Silver Hoop Earrings', 'oxidized-silver-hoop-earrings', 'Handcrafted oxidized silver hoop earrings with tribal etching patterns. Bold yet lightweight for comfortable all-day wear.', 24.99, 34.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er4/600/600'], 35, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['hoops', 'oxidized', 'tribal', 'lightweight']),
('Pearl Drop Earrings', 'pearl-drop-earrings', 'Classic pearl drop earrings with gold-plated French hook. Timeless sophistication for office wear and formal occasions.', 29.99, 39.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er5/600/600'], 38, false, true, 'Pearl', 'White', 'Office', 'Classic', ARRAY['pearl', 'drop', 'office', 'formal']),
('Meenakari Peacock Jhumkas', 'meenakari-peacock-jhumkas', 'Vibrant meenakari jhumka earrings with peacock motif in blue and green enamel. Handpainted details make each pair unique.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er6/600/600', 'https://picsum.photos/seed/er6b/600/600'], 22, true, true, 'Meenakari', 'Multi', 'Festival', 'Traditional', ARRAY['meenakari', 'peacock', 'jhumka', 'colorful']),
('Rose Gold Huggie Hoops', 'rose-gold-huggie-hoops', 'Dainty rose gold-plated huggie hoop earrings with micro pavé crystals. Chic and modern for the contemporary woman.', 22.99, 32.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er7/600/600'], 42, false, true, 'Gold Plated', 'Rose Gold', 'Daily Wear', 'Modern', ARRAY['huggie', 'hoops', 'rose-gold', 'dainty']),
('Temple Lakshmi Earrings', 'temple-lakshmi-earrings', 'Traditional temple-style earrings featuring Goddess Lakshmi motif with ruby and emerald stones. Perfect for pooja and temple visits.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er8/600/600'], 25, false, true, 'Temple', 'Gold', 'Festival', 'Traditional', ARRAY['temple', 'lakshmi', 'ruby', 'traditional']),
('Statement Tassel Earrings', 'statement-tassel-earrings', 'Show-stopping silk thread tassel earrings with crystal tops. Available-inspired by runway fashion with Indian craftsmanship.', 32.99, 44.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er9/600/600'], 30, false, true, 'Gold Plated', 'Multi', 'Party', 'Statement', ARRAY['tassel', 'statement', 'party', 'silk']),
('Kundan Polki Stud Earrings', 'kundan-polki-stud-earrings', 'Regal kundan polki stud earrings with uncut stone centers surrounded by tiny pearls. Sits flat against the earlobe for a refined look.', 49.99, 64.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er10/600/600'], 18, false, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['kundan', 'polki', 'studs', 'bridal']),
('Geometric Art Deco Earrings', 'geometric-art-deco-earrings', 'Art deco-inspired geometric earrings in silver plating with onyx accents. Where vintage glamour meets modern design.', 36.99, 49.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er11/600/600'], 28, false, true, 'Silver Plated', 'Silver', 'Party', 'Fusion', ARRAY['geometric', 'art-deco', 'vintage', 'modern']),
('Bridal Devsena Earrings', 'bridal-devsena-earrings', 'Inspired by Bollywood royalty — elaborate bridal earrings with ear chain (kan chain) connecting to hair. Multi-layered with pearls and stones.', 89.99, 119.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er12/600/600', 'https://picsum.photos/seed/er12b/600/600'], 10, false, true, 'Kundan', 'Gold', 'Bridal', 'Statement', ARRAY['bridal', 'devsena', 'ear-chain', 'bollywood']),
('Green Emerald Drop Earrings', 'green-emerald-drop-earrings', 'Elegant emerald green stone drop earrings with gold-plated settings and CZ halo. Adds a pop of color to any outfit.', 39.99, 54.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er13/600/600'], 32, false, true, 'Gold Plated', 'Green', 'Party', 'Modern', ARRAY['emerald', 'green', 'drop', 'party']),
('Oxidized Afghani Earrings', 'oxidized-afghani-earrings', 'Bold Afghani-inspired oxidized earrings with bell dangles and mirror work. Tribal chic for the free-spirited soul.', 27.99, 39.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er14/600/600'], 26, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['afghani', 'oxidized', 'mirror', 'tribal']),
('Pink Crystal Cluster Earrings', 'pink-crystal-cluster-earrings', 'Dazzling pink crystal cluster earrings that catch light from every angle. Perfect for date nights and special celebrations.', 31.99, 42.99, (SELECT id FROM categories WHERE slug = 'earrings'), ARRAY['https://picsum.photos/seed/er15/600/600'], 24, false, true, 'Gold Plated', 'Pink', 'Party', 'Modern', ARRAY['crystal', 'pink', 'cluster', 'party'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- BANGLES & BRACELETS (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Gold Plated Kada Set (4 pcs)', 'gold-plated-kada-set', 'Set of 4 gold-plated kadas with intricate carving and spring closure. Stackable design that creates a rich, layered look.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb1/600/600', 'https://picsum.photos/seed/bb1b/600/600'], 30, true, true, 'Gold Plated', 'Gold', 'Festival', 'Traditional', ARRAY['kada', 'set', 'stackable', 'gold']),
('Kundan Bridal Bangles (Set of 6)', 'kundan-bridal-bangles-set', 'Luxurious set of 6 kundan-studded bangles with alternating stone patterns. A must-have for the bride''s chooda ceremony look.', 99.99, 139.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb2/600/600', 'https://picsum.photos/seed/bb2b/600/600'], 15, true, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['kundan', 'bridal', 'bangles', 'set']),
('Silk Thread Bangles Rainbow Set', 'silk-thread-bangles-rainbow', 'Handmade silk thread bangles in a gorgeous rainbow color palette. Set of 12 thin bangles — mix and match to your outfit.', 24.99, 34.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb3/600/600'], 40, false, true, 'Gold Plated', 'Multi', 'Casual', 'Traditional', ARRAY['silk-thread', 'rainbow', 'handmade', 'colorful']),
('Oxidized Silver Cuff Bracelet', 'oxidized-silver-cuff-bracelet', 'Adjustable oxidized silver cuff bracelet with elephant motif engraving. One-size-fits-all with a comfortable open-back design.', 29.99, 39.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb4/600/600'], 35, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['cuff', 'oxidized', 'elephant', 'adjustable']),
('Pearl String Bracelet', 'pearl-string-bracelet', 'Delicate freshwater pearl string bracelet with gold-plated lobster clasp and extension chain. Adjustable 6.5" to 8" length.', 19.99, 27.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb5/600/600'], 42, false, true, 'Pearl', 'White', 'Daily Wear', 'Minimalist', ARRAY['pearl', 'bracelet', 'delicate', 'daily-wear']),
('Meenakari Rajasthani Bangles (Set of 8)', 'meenakari-rajasthani-bangles', 'Traditional Rajasthani meenakari bangles in red and green enamel on gold base. Set of 8 with matching stone patterns.', 49.99, 69.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb6/600/600', 'https://picsum.photos/seed/bb6b/600/600'], 25, true, true, 'Meenakari', 'Multi', 'Festival', 'Traditional', ARRAY['meenakari', 'rajasthani', 'enamel', 'festival']),
('Rose Gold Chain Bracelet', 'rose-gold-chain-bracelet', 'Modern rose gold-plated chain bracelet with tiny crystal charms. Lightweight and perfect for everyday wear — won''t snag on clothes.', 17.99, 24.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb7/600/600'], 48, false, true, 'Gold Plated', 'Rose Gold', 'Daily Wear', 'Modern', ARRAY['chain', 'rose-gold', 'charm', 'lightweight']),
('Temple Bangle Pair', 'temple-bangle-pair', 'Pair of temple-style bangles with Lakshmi and elephant motifs. Heavy-weight feel with a rich antique gold finish.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb8/600/600'], 20, false, true, 'Temple', 'Gold', 'Festival', 'Traditional', ARRAY['temple', 'pair', 'lakshmi', 'heavy']),
('Crystal Tennis Bracelet', 'crystal-tennis-bracelet', 'Stunning crystal tennis bracelet in silver plating with box clasp closure. Red carpet glamour for your wrist.', 39.99, 54.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb9/600/600'], 28, false, true, 'Silver Plated', 'Silver', 'Party', 'Modern', ARRAY['tennis', 'crystal', 'party', 'glamorous']),
('Lac Bangles Multicolor (Set of 24)', 'lac-bangles-multicolor-set', 'Traditional lac bangles handcrafted in Rajasthan. Set of 24 in assorted colors — the classic jingle-jangle bangles every wardrobe needs.', 34.99, 44.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb10/600/600'], 20, false, true, 'Gold Plated', 'Multi', 'Casual', 'Traditional', ARRAY['lac', 'rajasthani', 'multicolor', 'handcrafted']),
('Gold Charm Bracelet', 'gold-charm-bracelet', 'Gold-plated charm bracelet with dangling charms — evil eye, hamsa hand, lotus flower, and Om symbol. Meaningful and beautiful.', 32.99, 44.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb11/600/600'], 33, false, true, 'Gold Plated', 'Gold', 'Daily Wear', 'Fusion', ARRAY['charm', 'meaningful', 'evil-eye', 'spiritual']),
('Red & Green Bridal Chooda Set', 'red-green-bridal-chooda-set', 'Complete bridal chooda set in red and green with gold accents. Set of 20 bangles — traditional and auspicious for the new bride.', 79.99, 109.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb12/600/600', 'https://picsum.photos/seed/bb12b/600/600'], 12, false, true, 'Gold Plated', 'Red', 'Bridal', 'Traditional', ARRAY['chooda', 'bridal', 'red', 'green']),
('Oxidized Ghungroo Bangle', 'oxidized-ghungroo-bangle', 'Single statement oxidized bangle with tiny ghungroo (bell) attachments. Makes a delightful tinkling sound as you move.', 22.99, 29.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb13/600/600'], 30, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['ghungroo', 'bells', 'oxidized', 'statement']),
('Polki Open Cuff Bangle', 'polki-open-cuff-bangle', 'Elegant open cuff bangle with polki stone center and fine pearl borders. Adjustable to fit most wrist sizes.', 64.99, 84.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb14/600/600'], 18, false, true, 'Kundan', 'Gold', 'Wedding', 'Statement', ARRAY['polki', 'cuff', 'adjustable', 'wedding']),
('Thread & Stone Friendship Bracelets (3 pcs)', 'thread-stone-friendship-bracelets', 'Set of 3 colorful thread bracelets with semi-precious stone centers. Perfect for gifting or stacking with other bracelets.', 15.99, 22.99, (SELECT id FROM categories WHERE slug = 'bangles-bracelets'), ARRAY['https://picsum.photos/seed/bb15/600/600'], 50, false, true, 'Gold Plated', 'Multi', 'Casual', 'Boho', ARRAY['friendship', 'thread', 'stones', 'gift'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- PENDANT SETS (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Kundan Pendant Set with Earrings', 'kundan-pendant-set-earrings', 'Matching kundan pendant and earring set with teardrop design. The pendant features a central green stone surrounded by white kundan stones.', 89.99, 119.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps1/600/600', 'https://picsum.photos/seed/ps1b/600/600'], 20, true, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['kundan', 'pendant-set', 'matching', 'green']),
('Solitaire Diamond-Style Pendant', 'solitaire-diamond-style-pendant', 'Brilliant solitaire CZ pendant on a delicate silver-plated chain. The perfect everyday pendant that adds subtle sparkle.', 29.99, 39.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps2/600/600'], 40, true, true, 'Silver Plated', 'Silver', 'Daily Wear', 'Minimalist', ARRAY['solitaire', 'diamond', 'daily-wear', 'subtle']),
('Temple Pendant with Ear Studs', 'temple-pendant-ear-studs', 'South Indian temple-style pendant with matching ear studs. Features Goddess Lakshmi motif in antique gold finish.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps3/600/600', 'https://picsum.photos/seed/ps3b/600/600'], 22, false, true, 'Temple', 'Gold', 'Festival', 'Traditional', ARRAY['temple', 'lakshmi', 'pendant-set', 'antique']),
('Pearl Pendant with Drop Earrings', 'pearl-pendant-drop-earrings', 'Elegant freshwater pearl pendant paired with matching pearl drop earrings. Set in gold-plated mountings for a luxe feel.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps4/600/600'], 28, false, true, 'Pearl', 'White', 'Office', 'Classic', ARRAY['pearl', 'pendant', 'office', 'elegant']),
('Meenakari Locket Set', 'meenakari-locket-set', 'Colorful meenakari locket pendant with matching earrings in vibrant enamel. Opens to reveal space for a tiny photo inside.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps5/600/600', 'https://picsum.photos/seed/ps5b/600/600'], 18, true, true, 'Meenakari', 'Multi', 'Festival', 'Traditional', ARRAY['meenakari', 'locket', 'enamel', 'colorful']),
('Rose Gold Heart Pendant Set', 'rose-gold-heart-pendant-set', 'Romantic rose gold heart pendant with matching stud earrings. Micro CZ stones line the heart outline for extra sparkle.', 34.99, 44.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps6/600/600'], 35, false, true, 'Gold Plated', 'Rose Gold', 'Daily Wear', 'Modern', ARRAY['heart', 'rose-gold', 'romantic', 'cz']),
('Oxidized Owl Pendant Set', 'oxidized-owl-pendant-set', 'Quirky oxidized silver owl pendant on a leather cord with matching owl stud earrings. For the free spirit who loves nature.', 24.99, 34.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps7/600/600'], 30, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['owl', 'oxidized', 'leather', 'quirky']),
('Ruby Red Pendant & Earrings', 'ruby-red-pendant-earrings', 'Stunning ruby red stone pendant with halo setting and matching drop earrings. Gold-plated with a royal vintage appeal.', 69.99, 89.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps8/600/600'], 15, false, true, 'Gold Plated', 'Red', 'Party', 'Classic', ARRAY['ruby', 'red', 'vintage', 'halo']),
('Polki Navratna Pendant Set', 'polki-navratna-pendant-set', 'Traditional navratna (nine gems) pendant set with polki border. Each stone represents a celestial body — believed to bring good fortune.', 119.99, 159.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps9/600/600', 'https://picsum.photos/seed/ps9b/600/600'], 10, false, true, 'Kundan', 'Multi', 'Wedding', 'Traditional', ARRAY['navratna', 'nine-gems', 'polki', 'auspicious']),
('Minimalist Bar Pendant Set', 'minimalist-bar-pendant-set', 'Sleek horizontal bar pendant on a fine chain with matching geometric bar stud earrings. Clean lines for the modern minimalist.', 22.99, 29.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps10/600/600'], 45, false, true, 'Gold Plated', 'Gold', 'Office', 'Minimalist', ARRAY['bar', 'minimalist', 'geometric', 'office']),
('Emerald Green Pendant Set', 'emerald-green-pendant-set', 'Rich emerald green stone pendant set with matching studs. The stones are set in a gold-plated bezel for a clean, modern look.', 49.99, 64.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps11/600/600'], 25, false, true, 'Gold Plated', 'Green', 'Party', 'Modern', ARRAY['emerald', 'green', 'bezel', 'modern']),
('Bridal Kundan Pendant Heavy Set', 'bridal-kundan-pendant-heavy-set', 'Elaborate bridal kundan pendant set with layered pearl strings and matching chandbali earrings. A complete bridal look.', 149.99, 199.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps12/600/600', 'https://picsum.photos/seed/ps12b/600/600'], 8, false, true, 'Kundan', 'Gold', 'Bridal', 'Statement', ARRAY['bridal', 'heavy', 'kundan', 'layered']),
('Evil Eye Protection Pendant', 'evil-eye-protection-pendant', 'Blue evil eye pendant with matching earrings in gold-plated settings. A fusion of Turkish symbolism with Indian craftsmanship.', 27.99, 36.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps13/600/600'], 38, false, true, 'Gold Plated', 'Multi', 'Daily Wear', 'Fusion', ARRAY['evil-eye', 'protection', 'turkish', 'fusion']),
('Silver Moonstone Pendant Set', 'silver-moonstone-pendant-set', 'Ethereal moonstone pendant set in sterling silver-plated mountings with matching studs. The stone''s adularescence changes with light.', 42.99, 57.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps14/600/600'], 20, false, true, 'Silver Plated', 'White', 'Casual', 'Boho', ARRAY['moonstone', 'ethereal', 'silver', 'natural']),
('Statement Geometric Pendant Set', 'statement-geometric-pendant-set', 'Bold geometric pendant in gold-plated finish with matching angular earrings. Modern art meets wearable jewelry.', 37.99, 49.99, (SELECT id FROM categories WHERE slug = 'pendant-sets'), ARRAY['https://picsum.photos/seed/ps15/600/600'], 22, false, true, 'Gold Plated', 'Gold', 'Party', 'Statement', ARRAY['geometric', 'bold', 'art', 'modern'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- JADAU JEWELRY (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Jadau Kundan Necklace Set', 'jadau-kundan-necklace-set', 'Majestic jadau kundan necklace with matching earrings and tikka. Handcrafted by Rajasthani artisans with traditional lac and stone setting.', 249.99, 329.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj1/600/600', 'https://picsum.photos/seed/jj1b/600/600'], 8, true, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'necklace-set', 'rajasthani', 'handcrafted']),
('Jadau Chandbali Earrings', 'jadau-chandbali-earrings', 'Exquisite jadau chandbali earrings with emerald drops and pearl tassels. Each stone is individually set by hand in the jadau technique.', 129.99, 169.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj2/600/600', 'https://picsum.photos/seed/jj2b/600/600'], 12, true, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['jadau', 'chandbali', 'emerald', 'pearl']),
('Jadau Maang Tikka', 'jadau-maang-tikka', 'Traditional jadau maang tikka with central polki stone and pearl drops. Adds the perfect bridal touch to your parting.', 69.99, 89.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj3/600/600'], 20, true, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'maang-tikka', 'polki', 'bridal']),
('Jadau Choker with Pearls', 'jadau-choker-pearls', 'Stunning jadau choker necklace lined with natural pearl drops. Features red and green meenakari work on the reverse.', 189.99, 249.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj4/600/600', 'https://picsum.photos/seed/jj4b/600/600'], 10, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'choker', 'pearls', 'meenakari']),
('Jadau Ring with Ruby Center', 'jadau-ring-ruby-center', 'Ornate jadau ring with central ruby stone and surrounding polki stones. Adjustable band fits most finger sizes.', 49.99, 64.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj5/600/600'], 25, false, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['jadau', 'ring', 'ruby', 'adjustable']),
('Jadau Bajuband (Armlet)', 'jadau-bajuband-armlet', 'Traditional jadau bajuband (armlet) with peacock motif and hanging pearl tassels. Worn on the upper arm for bridal ceremonies.', 79.99, 109.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj6/600/600'], 15, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'bajuband', 'armlet', 'peacock']),
('Jadau Hathphool (Hand Chain)', 'jadau-hathphool-hand-chain', 'Intricate jadau hathphool connecting a ring to a bracelet via delicate chains. Features floral kundan motifs and pearl accents.', 89.99, 119.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj7/600/600'], 14, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'hathphool', 'hand-chain', 'floral']),
('Jadau Nose Ring (Nath)', 'jadau-nose-ring-nath', 'Elaborate jadau bridal nose ring (nath) with chain attachment and pearl drops. A signature bridal accessory in Indian weddings.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj8/600/600'], 18, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'nath', 'nose-ring', 'bridal']),
('Jadau Pendant Long Chain', 'jadau-pendant-long-chain', 'Jadau pendant on a long gold-plated chain. The pendant features a lotus motif with green and red stones — perfect for festive layering.', 74.99, 99.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj9/600/600'], 20, false, true, 'Kundan', 'Gold', 'Festival', 'Traditional', ARRAY['jadau', 'pendant', 'lotus', 'long-chain']),
('Jadau Anklet Pair (Payal)', 'jadau-anklet-pair-payal', 'Delicate jadau anklet pair with ghungroo bells and kundan stone settings. Musical anklets that add grace to every step.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj10/600/600'], 22, false, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['jadau', 'anklet', 'payal', 'ghungroo']),
('Jadau Passa (Side Tikka)', 'jadau-passa-side-tikka', 'Traditional jadau passa (jhoomar) worn on the side of the forehead. Cascading pearl strings with kundan centerpiece.', 64.99, 84.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj11/600/600'], 16, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['jadau', 'passa', 'jhoomar', 'side-tikka']),
('Jadau Waist Chain (Kamarband)', 'jadau-waist-chain-kamarband', 'Ornate jadau kamarband (waist chain) with multiple kundan motifs connected by pearl strings. Adds elegance to lehengas and sarees.', 139.99, 179.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj12/600/600', 'https://picsum.photos/seed/jj12b/600/600'], 8, false, true, 'Kundan', 'Gold', 'Bridal', 'Statement', ARRAY['jadau', 'kamarband', 'waist-chain', 'lehenga']),
('Mini Jadau Stud Earrings', 'mini-jadau-stud-earrings', 'Petite jadau stud earrings with a single polki center and tiny pearl border. Perfect for daily wear — brings tradition to everyday style.', 34.99, 44.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj13/600/600'], 35, false, true, 'Kundan', 'Gold', 'Daily Wear', 'Classic', ARRAY['jadau', 'studs', 'mini', 'daily-wear']),
('Jadau Mathapatti (Forehead Band)', 'jadau-mathapatti-forehead-band', 'Showstopping jadau mathapatti that drapes across the forehead with side chains. Central medallion with cascading pearl drops.', 109.99, 149.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj14/600/600', 'https://picsum.photos/seed/jj14b/600/600'], 10, false, true, 'Kundan', 'Gold', 'Bridal', 'Statement', ARRAY['jadau', 'mathapatti', 'forehead', 'bridal']),
('Jadau Brooch Pin', 'jadau-brooch-pin', 'Versatile jadau brooch pin with floral motif. Can be worn on saree pallu, shawl, or blazer for a touch of traditional elegance.', 39.99, 52.99, (SELECT id FROM categories WHERE slug = 'jadau-jewelry'), ARRAY['https://picsum.photos/seed/jj15/600/600'], 30, false, true, 'Kundan', 'Gold', 'Festival', 'Fusion', ARRAY['jadau', 'brooch', 'pin', 'versatile'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- HAIR ACCESSORIES (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Kundan Maang Tikka Classic', 'kundan-maang-tikka-classic', 'Classic kundan maang tikka with single drop and pearl surround. An essential accessory for every Indian celebration.', 29.99, 39.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha1/600/600', 'https://picsum.photos/seed/ha1b/600/600'], 35, true, true, 'Kundan', 'Gold', 'Wedding', 'Traditional', ARRAY['maang-tikka', 'kundan', 'bridal', 'classic']),
('Crystal Juda Pin Set (3 pcs)', 'crystal-juda-pin-set', 'Set of 3 crystal-studded juda (bun) pins in gold-plated settings. Transforms any bun hairstyle into a bridal masterpiece.', 24.99, 34.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha2/600/600'], 40, true, true, 'Gold Plated', 'Gold', 'Wedding', 'Classic', ARRAY['juda-pin', 'bun', 'crystal', 'bridal']),
('Pearl Hair Chain (Matha Patti)', 'pearl-hair-chain-matha-patti', 'Elegant pearl hair chain that drapes from center parting to both sides of the head. Adjustable hooks fit all head sizes.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha3/600/600'], 22, true, true, 'Pearl', 'White', 'Bridal', 'Traditional', ARRAY['hair-chain', 'matha-patti', 'pearl', 'adjustable']),
('Flower Hair Clips (Set of 6)', 'flower-hair-clips-set', 'Charming artificial flower hair clips in assorted colors — red, pink, white, yellow, orange, and purple. Perfect for mehendi or sangeet.', 17.99, 24.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha4/600/600'], 45, false, true, 'Gold Plated', 'Multi', 'Festival', 'Traditional', ARRAY['flower', 'clips', 'mehendi', 'colorful']),
('Oxidized Hair Comb', 'oxidized-hair-comb', 'Ornate oxidized silver hair comb with peacock motif. Slides into any updo to add vintage character and hold.', 19.99, 27.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha5/600/600'], 30, false, true, 'Oxidized', 'Silver', 'Casual', 'Boho', ARRAY['hair-comb', 'peacock', 'oxidized', 'vintage']),
('Bridal Jhoomar (Side Passa)', 'bridal-jhoomar-side-passa', 'Statement bridal jhoomar with cascading strings and kundan centerpiece. Worn on the side of the head for a royal bridal look.', 69.99, 94.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha6/600/600', 'https://picsum.photos/seed/ha6b/600/600'], 14, false, true, 'Kundan', 'Gold', 'Bridal', 'Statement', ARRAY['jhoomar', 'passa', 'bridal', 'royal']),
('Gold Hair Vine (Flexible)', 'gold-hair-vine-flexible', 'Flexible gold-plated hair vine with tiny crystal buds and leaves. Can be twisted into braids, buns, or worn as a headband.', 34.99, 47.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha7/600/600'], 25, false, true, 'Gold Plated', 'Gold', 'Wedding', 'Modern', ARRAY['hair-vine', 'flexible', 'crystal', 'versatile']),
('Gajra Hair Garland (Artificial)', 'gajra-hair-garland-artificial', 'Realistic artificial jasmine gajra for hair decoration. Reusable, fragrance-free, and perfect for every Indian occasion.', 12.99, 17.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha8/600/600'], 50, false, true, 'Gold Plated', 'White', 'Festival', 'Traditional', ARRAY['gajra', 'jasmine', 'garland', 'reusable']),
('Meenakari Hair Pin Pair', 'meenakari-hair-pin-pair', 'Pair of meenakari hair pins with intricate floral enamel work. A pop of color to brighten up traditional hairstyles.', 16.99, 22.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha9/600/600'], 38, false, true, 'Meenakari', 'Multi', 'Festival', 'Traditional', ARRAY['meenakari', 'hair-pin', 'enamel', 'floral']),
('Crystal Tiara Crown', 'crystal-tiara-crown', 'Sparkling crystal tiara crown for brides and special occasions. Lightweight aluminum base with CZ stones and pearl accents.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha10/600/600'], 15, false, true, 'Silver Plated', 'Silver', 'Bridal', 'Modern', ARRAY['tiara', 'crown', 'crystal', 'princess']),
('Silk Thread Parandi', 'silk-thread-parandi', 'Traditional Punjabi silk thread parandi (hair braid accessory) in red and gold. Weaves into your braid for a festive look.', 14.99, 19.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha11/600/600'], 42, false, true, 'Gold Plated', 'Red', 'Festival', 'Traditional', ARRAY['parandi', 'punjabi', 'braid', 'silk']),
('Rose Gold Bobby Pins Crystal (Set of 10)', 'rose-gold-bobby-pins-crystal-set', 'Set of 10 rose gold bobby pins with tiny crystal ends. Functional and decorative — secures hair while adding sparkle.', 15.99, 21.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha12/600/600'], 48, false, true, 'Gold Plated', 'Rose Gold', 'Daily Wear', 'Minimalist', ARRAY['bobby-pins', 'rose-gold', 'crystal', 'daily-wear']),
('Bridal Hair Brooch Large', 'bridal-hair-brooch-large', 'Large bridal hair brooch with kundan stones and pearl dangles. Pins into a bun to create a stunning focal point for the hairstyle.', 39.99, 54.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha13/600/600'], 20, false, true, 'Kundan', 'Gold', 'Bridal', 'Traditional', ARRAY['brooch', 'bun', 'kundan', 'bridal']),
('Headband Chain Gold', 'headband-chain-gold', 'Minimalist gold-plated headband chain that sits across the forehead. Modern take on the traditional borla for a fusion look.', 22.99, 29.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha14/600/600'], 28, false, true, 'Gold Plated', 'Gold', 'Party', 'Fusion', ARRAY['headband', 'chain', 'borla', 'fusion']),
('Temple Choti Pin Set', 'temple-choti-pin-set', 'Set of temple-style choti pins for braided hair. Features traditional South Indian motifs — sun, moon, and temple tower designs.', 32.99, 42.99, (SELECT id FROM categories WHERE slug = 'hair-accessories'), ARRAY['https://picsum.photos/seed/ha15/600/600'], 25, false, true, 'Temple', 'Gold', 'Festival', 'Traditional', ARRAY['choti', 'braid', 'temple', 'south-indian'])
ON CONFLICT (slug) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- DRESSES (15)
-- ══════════════════════════════════════════════════════════════════════════════
INSERT INTO products (name, slug, description, price, compare_price, category_id, images, stock_quantity, featured, active, material, color, occasion, style, tags) VALUES
('Embroidered Anarkali Suit', 'embroidered-anarkali-suit', 'Floor-length Anarkali suit in rich maroon with gold zari embroidery. Comes with matching dupatta and churidar bottom. Available in S/M/L/XL.', 129.99, 169.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr1/600/600', 'https://picsum.photos/seed/dr1b/600/600'], 15, true, true, 'Gold Plated', 'Red', 'Wedding', 'Traditional', ARRAY['anarkali', 'embroidered', 'zari', 'maroon']),
('Designer Lehenga Choli', 'designer-lehenga-choli', 'Stunning teal and gold lehenga choli with sequin work and net dupatta. Semi-stitched for custom fitting. Perfect for weddings and receptions.', 249.99, 329.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr2/600/600', 'https://picsum.photos/seed/dr2b/600/600'], 10, true, true, 'Gold Plated', 'Multi', 'Bridal', 'Traditional', ARRAY['lehenga', 'choli', 'sequin', 'teal']),
('Banarasi Silk Saree', 'banarasi-silk-saree', 'Pure Banarasi-style silk saree in royal purple with intricate gold jaal weave. Includes matching blouse piece. Drapes beautifully.', 179.99, 229.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr3/600/600', 'https://picsum.photos/seed/dr3b/600/600'], 12, true, true, 'Gold Plated', 'Multi', 'Wedding', 'Traditional', ARRAY['banarasi', 'saree', 'silk', 'purple']),
('Cotton Kurti with Palazzo', 'cotton-kurti-palazzo', 'Comfortable cotton kurti in mustard yellow with block print and matching palazzo pants. Perfect for daily wear and casual outings.', 39.99, 54.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr4/600/600'], 35, false, true, 'Gold Plated', 'Gold', 'Daily Wear', 'Casual', ARRAY['kurti', 'palazzo', 'cotton', 'block-print']),
('Sharara Suit Festive', 'sharara-suit-festive', 'Gorgeous sharara suit in dusty pink with mirror and thread work. Flared sharara bottoms create a stunning silhouette for festive occasions.', 99.99, 129.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr5/600/600', 'https://picsum.photos/seed/dr5b/600/600'], 18, false, true, 'Gold Plated', 'Pink', 'Festival', 'Traditional', ARRAY['sharara', 'mirror-work', 'pink', 'festive']),
('Indo-Western Gown', 'indo-western-gown', 'Elegant indo-western gown in midnight blue with gold embroidery on bodice. Floor-length with a flowing silhouette — modern meets traditional.', 159.99, 199.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr6/600/600'], 14, false, true, 'Gold Plated', 'Multi', 'Party', 'Fusion', ARRAY['gown', 'indo-western', 'blue', 'evening']),
('Printed Salwar Kameez', 'printed-salwar-kameez', 'Vibrant printed salwar kameez in cotton blend with paisley motifs. Includes dupatta and straight-cut salwar. Easy-care fabric.', 44.99, 59.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr7/600/600'], 30, false, true, 'Gold Plated', 'Multi', 'Casual', 'Traditional', ARRAY['salwar', 'kameez', 'printed', 'paisley']),
('Georgette Party Saree', 'georgette-party-saree', 'Lightweight georgette saree in rose gold with crystal stone border. Pre-pleated for easy draping. Ready to wear in minutes.', 89.99, 119.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr8/600/600'], 20, false, true, 'Gold Plated', 'Rose Gold', 'Party', 'Modern', ARRAY['georgette', 'saree', 'pre-pleated', 'party']),
('Straight Kurta with Dupatta', 'straight-kurta-dupatta', 'Elegant straight-cut kurta in sage green with white chikankari embroidery. Comes with matching cotton dupatta. Perfect for office and casual wear.', 34.99, 44.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr9/600/600'], 28, false, true, 'Gold Plated', 'Green', 'Office', 'Classic', ARRAY['kurta', 'chikankari', 'green', 'office']),
('Bridal Red Lehenga Heavy', 'bridal-red-lehenga-heavy', 'Show-stopping bridal red lehenga with heavy zardozi embroidery in gold and silver. Complete set with blouse and dupatta. Semi-stitched.', 299.99, null, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr10/600/600', 'https://picsum.photos/seed/dr10b/600/600'], 5, false, true, 'Gold Plated', 'Red', 'Bridal', 'Traditional', ARRAY['bridal', 'lehenga', 'red', 'zardozi']),
('Dhoti Kurta Set (Men''s Style)', 'dhoti-kurta-set-womens', 'Trendy dhoti-style pants with short kurta top. A modern twist on the traditional dhoti — comfortable and fashion-forward.', 54.99, 74.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr11/600/600'], 25, false, true, 'Gold Plated', 'Gold', 'Festival', 'Fusion', ARRAY['dhoti', 'kurta', 'fusion', 'trendy']),
('Chanderi Silk Suit', 'chanderi-silk-suit', 'Exquisite Chanderi silk suit in ivory with gold tissue borders. Lightweight and luxurious for summer celebrations and pooja ceremonies.', 119.99, 159.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr12/600/600'], 16, false, true, 'Gold Plated', 'White', 'Festival', 'Classic', ARRAY['chanderi', 'silk', 'ivory', 'lightweight']),
('Palazzo Suit with Jacket', 'palazzo-suit-jacket', 'Three-piece palazzo suit with embroidered jacket overlay in navy and gold. Modern styling for reception parties and formal events.', 79.99, 99.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr13/600/600'], 22, false, true, 'Gold Plated', 'Multi', 'Party', 'Fusion', ARRAY['palazzo', 'jacket', 'three-piece', 'formal']),
('Bandhani Print Saree', 'bandhani-print-saree', 'Traditional bandhani (tie-dye) saree from Gujarat in vibrant red and yellow. Pure synthetic blend with golden border. Festive perfection.', 59.99, 79.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr14/600/600'], 20, false, true, 'Gold Plated', 'Red', 'Festival', 'Traditional', ARRAY['bandhani', 'tie-dye', 'saree', 'gujarati']),
('A-Line Kurta Minimal', 'a-line-kurta-minimal', 'Clean A-line kurta in solid white with subtle gold buttons. Perfect minimalist piece for building any Indian outfit — versatile and elegant.', 29.99, 39.99, (SELECT id FROM categories WHERE slug = 'dresses'), ARRAY['https://picsum.photos/seed/dr15/600/600'], 40, false, true, 'Gold Plated', 'White', 'Daily Wear', 'Minimalist', ARRAY['a-line', 'kurta', 'minimal', 'white'])
ON CONFLICT (slug) DO NOTHING;
